// <auto-generated />
using System;
using GMSApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GMSApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250805210201_Initial2")]
    partial class Initial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("GMSApp.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mainid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Mainid");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("GMSApp.Models.CoreMain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("FooterFile")
                        .HasColumnType("BLOB");

                    b.Property<string>("FooterName")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("HeaderFile")
                        .HasColumnType("BLOB");

                    b.Property<string>("HeaderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CoreMains");
                });

            modelBuilder.Entity("GMSApp.Models.FileItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("GMSApp.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mainid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Mainid");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("GMSApp.Models.ItemRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("ItemRows");
                });

            modelBuilder.Entity("GMSApp.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mainid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Mainid");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("GMSApp.Models.Main", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoreMainId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LabelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CoreMainId");

                    b.HasIndex("LabelId");

                    b.HasIndex("TypeId");

                    b.ToTable("Mains");
                });

            modelBuilder.Entity("GMSApp.Models.Main+Labels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductlabelsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("inventorylabelsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("invoicelabelsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quotationlabelsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("vendorlabelsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductlabelsId");

                    b.HasIndex("inventorylabelsId");

                    b.HasIndex("invoicelabelsId");

                    b.HasIndex("quotationlabelsId");

                    b.HasIndex("vendorlabelsId");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("GMSApp.Models.Main+inventorylabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("inventorylabel");
                });

            modelBuilder.Entity("GMSApp.Models.Main+invoicelabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("invoicelabel");
                });

            modelBuilder.Entity("GMSApp.Models.Main+productlabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("productlabel");
                });

            modelBuilder.Entity("GMSApp.Models.Main+quotationlabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("quotationlabel");
                });

            modelBuilder.Entity("GMSApp.Models.Main+vendorlabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("vendorlabel");
                });

            modelBuilder.Entity("GMSApp.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mainid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Mainid");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("GMSApp.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("GMSApp.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("GMSApp.Models.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("GMSApp.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MainId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MainId");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("GMSApp.Models.Vendor+Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("phone")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("GMSApp.Models.Vendor+VendorData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("VendorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorData");
                });

            modelBuilder.Entity("GMSApp.Models.Account", b =>
                {
                    b.HasOne("GMSApp.Models.Main", "Main")
                        .WithMany("Accounts")
                        .HasForeignKey("Mainid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Main");
                });

            modelBuilder.Entity("GMSApp.Models.Inventory", b =>
                {
                    b.HasOne("GMSApp.Models.Main", "Main")
                        .WithMany("Inventories")
                        .HasForeignKey("Mainid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Main");
                });

            modelBuilder.Entity("GMSApp.Models.ItemRow", b =>
                {
                    b.HasOne("GMSApp.Models.PurchaseOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GMSApp.Models.Job", b =>
                {
                    b.HasOne("GMSApp.Models.Main", "Main")
                        .WithMany("Jobs")
                        .HasForeignKey("Mainid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Main");
                });

            modelBuilder.Entity("GMSApp.Models.Main", b =>
                {
                    b.HasOne("GMSApp.Models.CoreMain", "CoreMain")
                        .WithMany("Main")
                        .HasForeignKey("CoreMainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GMSApp.Models.Main+Labels", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId");

                    b.HasOne("GMSApp.Models.Type", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("CoreMain");

                    b.Navigation("Label");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("GMSApp.Models.Main+Labels", b =>
                {
                    b.HasOne("GMSApp.Models.Main+productlabel", "Productlabels")
                        .WithMany()
                        .HasForeignKey("ProductlabelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GMSApp.Models.Main+inventorylabel", "inventorylabels")
                        .WithMany()
                        .HasForeignKey("inventorylabelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GMSApp.Models.Main+invoicelabel", "invoicelabels")
                        .WithMany()
                        .HasForeignKey("invoicelabelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GMSApp.Models.Main+quotationlabel", "quotationlabels")
                        .WithMany()
                        .HasForeignKey("quotationlabelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GMSApp.Models.Main+vendorlabel", "vendorlabels")
                        .WithMany()
                        .HasForeignKey("vendorlabelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Productlabels");

                    b.Navigation("inventorylabels");

                    b.Navigation("invoicelabels");

                    b.Navigation("quotationlabels");

                    b.Navigation("vendorlabels");
                });

            modelBuilder.Entity("GMSApp.Models.Payment", b =>
                {
                    b.HasOne("GMSApp.Models.Main", "Main")
                        .WithMany("Payments")
                        .HasForeignKey("Mainid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Main");
                });

            modelBuilder.Entity("GMSApp.Models.Vendor", b =>
                {
                    b.HasOne("GMSApp.Models.Main", "Main")
                        .WithMany("Vendors")
                        .HasForeignKey("MainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Main");
                });

            modelBuilder.Entity("GMSApp.Models.Vendor+VendorData", b =>
                {
                    b.HasOne("GMSApp.Models.Vendor+Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GMSApp.Models.Vendor", null)
                        .WithMany("Vendors")
                        .HasForeignKey("VendorId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("GMSApp.Models.CoreMain", b =>
                {
                    b.Navigation("Main");
                });

            modelBuilder.Entity("GMSApp.Models.Main", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Inventories");

                    b.Navigation("Jobs");

                    b.Navigation("Payments");

                    b.Navigation("Vendors");
                });

            modelBuilder.Entity("GMSApp.Models.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GMSApp.Models.Vendor", b =>
                {
                    b.Navigation("Vendors");
                });
#pragma warning restore 612, 618
        }
    }
}
